/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../../cv02/Device/ST/STM32F0xx/Include/stm32f0xx.h"
#include "sct.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define LED_TIME_BLINK 300
#define LED_TIME_SHORT 100
#define LED_TIME_LONG 1000
#define SAMPLING_PERIOD 40
#define DEBOUNCE_PERIOD 5

volatile uint32_t tick;

void SysTick_Handler(void)
{
	tick++;
}

//void EXTI0_1_IRQHandler(void)
//{
//
//	if (EXTI->PR & EXTI_PR_PR0)
//	{ // check line 0 has triggered the IT
//		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
//		GPIOB->ODR ^= (1<<0);
//	}
//}


int main(void)
{
	sct_init();
	sct_led(0x7A5C36DE);
    /* Loop forever */
	for(;;) {

	}
}

